BASE_PATH: ./
DEBUG: true
GOOGLE_SCOPES:
- https://www.googleapis.com/auth/presentations
- https://www.googleapis.com/auth/drive.file
IMAGE_GENERATION_MODEL: stabilityai/stable-diffusion-2-1
IMAGE_STORAGE_SERVICE: GoogleDrive
IMGUR_CLIENT_ID: d50cc113493324b
LANGUAGE: en
SENTENCE_ENCODERS:
- en: https://tfhub.dev/google/universal-sentence-encoder/4
SUMMARIZATION_MODEL: philschmid/flan-t5-base-samsum

TITLE_GENERATION_MODEL: deep-learning-analytics/automatic-title-generation
